name: Lint check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint check
        run: yarn lint
