name: Build and deploy storybook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build storybook
        run: yarn build:storybook
      - name: Push storybook to Github Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          user-email: tarunveers3@gmail.com
          source-directory: storybook-static
          destination-github-username: thetorine
          destination-repository-name: thetorine.github.io
          target-branch: main
          target-directory: projects/react-graph-library
